name: git-update-actions
on: [push]
jobs:
  check-git-env:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: pwd
      - run: git config --list